# Generated by Django 4.0.1 on 2022-07-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('day', models.TextField(blank=True, null=True)),
                ('solved_date', models.TextField(blank=True, null=True)),
                ('elapsed_seconds', models.IntegerField(blank=True, null=True)),
                ('solved', models.IntegerField(blank=True, null=True)),
                ('checked', models.IntegerField(blank=True, null=True)),
                ('revealed', models.IntegerField(blank=True, null=True)),
                ('streak_eligible', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'results',
            },
        ),
    ]
